name: Build, Test and publish to maven repo on Master Push

# Controls when the action will run.
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: "Publish verified jars"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build and Test
        run: ./gradlew test
      - name: Run acceptanceTests
        run: ./gradlew acceptancetest
        env:
          OCTOPUS_LICENSE: ${{ secrets.OCTOPUS_LICENSE }}
          OCTOPUS_SDK_AT_USE_EXISTING_SERVER: false
      - name: Publish to Maven
        run: ./gradlew artifactoryPublish
